### ISSUE TITLE
Bug: Dark Mode toggle color doesn't match

### ISSUE THREAD

**Issue by itsnandy** [yuuiko/AquaTouch#56]
In the control center of AQT, the dark mode toggle that is in between True Tone and Display sleep is a darker blue than the one between DND and the Play section of AQT. If you could make the darker one (toggled) the main color, that would be great.

**Comment by yuuiko** [comment]
The colours are the same, the lighter appearance of the sticky right one is probably because of its lighter background.

Regardless, I've increased it's icon size as that didn't match. Darkening the colour to "visually match" the scrollable one would result in a poor contrast and it being difficult to see on its lighter background. 

Thanks for this report though!
