### ISSUE TITLE
Feature Request: Localization in different languages

### ISSUE THREAD

**Issue by Vinz87** [yuuiko/AquaTouch#81]
Hi, what about localization in my own language (italian)? I tried to replace all the apps names in the "unsupported app" group, and in each of the affected groups, but still in BTT I see the message "your custom touchbar is hidden" for apps that change name in different languages (all Apple's ones, i.e. Notes, Calculator, Calendar, Messagges, etc.)

Would it be relatively easy to substitute app names strings with variables, which could be tuned accordingly?

**Comment by yuuiko** [comment]
BTT doesn't support localisation within presets, the preset would need to be completely rewritten in the new language as a new copy... 

I would love to support localisation, but due to BTT I don't think it can be done efficiently...

Even if i were to open volunteer translation, the entire preset would need to be re-created exactly for every AQT update released, I don't think many people have time for that.
